#include "ext_types.h"
static DataTypeInfo rtDataTypeInfoTable [ ] = { { "real_T" , 0 , 8 } , {
"real32_T" , 1 , 4 } , { "int8_T" , 2 , 1 } , { "uint8_T" , 3 , 1 } , {
"int16_T" , 4 , 2 } , { "uint16_T" , 5 , 2 } , { "int32_T" , 6 , 4 } , {
"uint32_T" , 7 , 4 } , { "boolean_T" , 8 , 1 } , { "fcn_call_T" , 9 , 0 } , {
"int_T" , 10 , 4 } , { "pointer_T" , 11 , 8 } , { "action_T" , 12 , 8 } , {
"timer_uint32_pair_T" , 13 , 8 } , { "physical_connection" , 14 , 8 } , {
"int64_T" , 15 , 8 } , { "uint64_T" , 16 , 8 } , {
"struct_P2gOKFVI6LTnqVOqokOdAB" , 17 , 1617904 } , { "string" , 18 , 8 } , {
"string" , 19 , 8 } , { "NextState" , 20 , 4 } , { "ssbus" , 21 , 1617904 } ,
{ "uint64_T" , 22 , 8 } , { "int64_T" , 23 , 8 } , { "uint_T" , 24 , 32 } , {
"char_T" , 25 , 8 } , { "uchar_T" , 26 , 8 } , { "time_T" , 27 , 8 } } ;
static uint_T rtDataTypeSizes [ ] = { sizeof ( real_T ) , sizeof ( real32_T )
, sizeof ( int8_T ) , sizeof ( uint8_T ) , sizeof ( int16_T ) , sizeof ( uint16_T ) , sizeof ( int32_T ) , sizeof ( uint32_T ) , sizeof ( boolean_T ) , sizeof ( fcn_call_T ) , sizeof ( int_T ) , sizeof ( pointer_T ) , sizeof ( action_T ) , 2 * sizeof ( uint32_T ) , sizeof ( int32_T ) , sizeof ( int64_T ) , sizeof ( uint64_T ) , sizeof ( int32_T ) , 8 , sizeof ( char_T ) , sizeof ( NextState ) , sizeof ( ssbus ) , sizeof ( uint64_T ) , sizeof ( int64_T ) , sizeof ( uint_T ) , sizeof ( char_T ) , sizeof ( uchar_T ) , sizeof ( time_T ) } ; static const char_T * rtDataTypeNames [ ] = { "real_T" , "real32_T" , "int8_T" , "uint8_T" , "int16_T" , "uint16_T" , "int32_T" , "uint32_T" , "boolean_T" , "fcn_call_T" , "int_T" , "pointer_T" , "action_T" , "timer_uint32_pair_T" , "physical_connection" , "int64_T" , "uint64_T" , "struct_P2gOKFVI6LTnqVOqokOdAB" , "string" , "string" , "NextState" , "ssbus" , "uint64_T" , "int64_T" , "uint_T" , "char_T" , "uchar_T" , "time_T" } ; static DataTypeTransition rtBTransitions [ ] = { { ( char_T * ) ( & rtB . cngfn1wxw4 ) , 0 , 0 , 56 } , { ( char_T * ) ( & rtB . dv5fmxftb2 ) , 8 , 0 , 7 } , { ( char_T * ) ( & rtDW . e2tyz0qrrq ) , 0 , 0 , 86 } , { ( char_T * ) ( & rtDW . dcnvswfsji . LoggedData [ 0 ] ) , 11 , 0 , 15 } , { ( char_T * ) ( & rtDW . kjbt4d23ke ) , 6 , 0 , 11 } , { ( char_T * ) ( & rtDW . lhfc0ta5ml ) , 7 , 0 , 2 } , { ( char_T * ) ( & rtDW . k5vzkvexn5 ) , 20 , 0 , 1 } , { ( char_T * ) ( & rtDW . hgyf2n5vgw ) , 2 , 0 , 5 } , { ( char_T * ) ( & rtDW . k00pa3laqh ) , 3 , 0 , 6 } , { ( char_T * ) ( & rtDW . bt4dt4cuu2 ) , 8 , 0 , 37 } } ; static DataTypeTransitionTable rtBTransTable = { 10U , rtBTransitions } ; static DataTypeTransition rtPTransitions [ ] = { { ( char_T * ) ( & rtP . simstruct ) , 21 , 0 , 1 } , { ( char_T * ) ( & rtP . LowPassFilterDiscreteorContinuous3_K ) , 0 , 0 , 53 } , { ( char_T * ) ( & rtP . OLED_STRING1_String ) , 11 , 0 , 2 } } ; static DataTypeTransitionTable rtPTransTable = { 3U , rtPTransitions } ;
